### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by blackjacket996** [wg-perception/people#105]
when I catkin_make , errors occur like this:

CMakeFiles/leg_detector.dir/src/leg_detector.cpp.o: In function `LegDetector::laserCallback(boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const> const&)':
leg_detector.cpp:(.text._ZN11LegDetector13laserCallbackERKN5boost10shared_ptrIKN11sensor_msgs10LaserScan_ISaIvEEEEE[_ZN11LegDetector13laserCallbackERKN5boost10shared_ptrIKN11sensor_msgs10LaserScan_ISaIvEEEEE]+0x4ca): undefined reference to `cv::ml::RTrees::getVotes(cv::_InputArray const&, cv::_OutputArray const&, int) const'
collect2: error: ld returned 1 exit status
people/leg_detector/CMakeFiles/leg_detector.dir/build.make:215: recipe for target '/home/joao-nisa/catkin_ws/devel/lib/leg_detector/leg_detector' failed
make[2]: *** [/home/joao-nisa/catkin_ws/devel/lib/leg_detector/leg_detector] Error 1
CMakeFiles/Makefile2:4646: recipe for target 'people/leg_detector/CMakeFiles/leg_detector.dir/all' failed
make[1]: *** [people/leg_detector/CMakeFiles/leg_detector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target face_detector
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

I'm using Ros-melodic & Ubuntu 18.04,and I saw a same question in issues , but I do not understand the solution "rolling it back".

**Comment by DLu** [comment]
What branch do you have checked out?

**Comment by blackjacket996** [comment]
Thank you so much for your reply. I've solved it ,but still thank you very much&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wg-perception/people"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 凌晨4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wg-perception/people] catkin_make error (Issue #105)





 
What branch do you have checked out?

**Comment by blackjacket996** [comment]
> What branch do you have checked out?

I've solved it ! Still thank you so much!

**Comment by blackjacket996** [comment]
Sry, I met a similar problem in ROS noetic && Ubuntu20.04. "undefined reference to cv::Mat::Mat(int, int, int), it shows there is something wrong in function"LegDetector::LaserCallback()" in leg_detector.cpp
