### ISSUE TITLE
release deb package on groovy

### ISSUE THREAD

**Issue by garaemon** [wg-perception/people#11]
Is is possible to release deb package on groovy?

**Comment by DLu** [comment]
@dlaz Can you see if we have any compilation issues preventing this?

**Comment by dlaz** [comment]
@garaemon, which branch did you want in groovy? I'm hesitant to use groovy-devel since it still uses rosbuild, but hydro-devel would require @DLu to release some other packages for groovy.

**Comment by garaemon** [comment]
hydro-devel branch looks good to me.

2014年8月13日水曜日、Dan Lazewatskynotifications@github.comさんは書きました:

> @garaemon https://github.com/garaemon, which branch did you want in
> groovy? I'm hesitant to use groovy-devel since it still uses rosbuild, but
> hydro-devel would require @DLu https://github.com/DLu to release some
> other packages for groovy.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wg-perception/people/issues/11#issuecomment-51945412.

## 

from iPhone

**Comment by DLu** [comment]
hydro-devel compiles under groovy on my machine. Give it a push?

**Comment by dlaz** [comment]
@DLu, can you release map_laser and kalman_filter for groovy first?

**Comment by DLu** [comment]
Pull requests have been merged for both. They should be ready shortly. 

My previous statement was false. hydro-devel won't compile unless you use the groovy version of layered costmaps. I've created the groovy branch that doesn't have the layered costmap.

**Comment by garaemon** [comment]
thanks!

-- ryohei

**Comment by DLu** [comment]
Should be all set now.

**Comment by garaemon** [comment]
rosdep says people apt packages exist, however it seems that no apt packages are released yet.

```
$ ROS_DISTRO=groovy rosdep db | grep people
people_tracking_filter -> ros-groovy-people-tracking-filter
people_msgs -> ros-groovy-people-msgs
people_velocity_tracker -> ros-groovy-people-velocity-tracker
people -> ros-groovy-people
$ aptitude search people
i A libpcl-people-1.7                              - The Point Cloud Library (or PCL) for point cloud processi
p   libpcl-people-1.7:i386                         - The Point Cloud Library (or PCL) for point cloud processi
i A libpcl-people-1.7-dev                          - The Point Cloud Library (or PCL) for point cloud processi
p   libpcl-people-1.7-dev:i386                     - The Point Cloud Library (or PCL) for point cloud processi
p   ros-fuerte-people                              - people                                                   
p   ros-fuerte-people:i386                         - people                                                   
p   ros-groovy-people                              - people                                                   
p   ros-groovy-people:i386                         - people                                                   
p   ros-hydro-people                               - The people stack holds algorithms for perceiving people f
p   ros-hydro-people:i386                          - The people stack holds algorithms for perceiving people f
i   ros-hydro-people-msgs                          - Messages used by nodes in the people stack.              
p   ros-hydro-people-msgs:i386                     - Messages used by nodes in the people stack.              
p   ros-hydro-people-tracking-filter               - A collection of filtering tools for tracking people's loc
p   ros-hydro-people-tracking-filter:i386          - A collection of filtering tools for tracking people's loc
p   ros-hydro-people-velocity-tracker              - Track the output of the leg_detector to indicate the velo
p   ros-hydro-people-velocity-tracker:i386         - Track the output of the leg_detector to indicate the velo

```

**Comment by DLu** [comment]
http://www.ros.org/debbuild/groovy.html?q=people&s=2

It should be out there with the next groovy release.

**Comment by garaemon** [comment]
@Dlu thanks!
