### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by DLu** [wg-perception/people#14]
via http://answers.ros.org/question/196490/people-tracker-detection-indigo/

**Comment by DLu** [comment]
@dlaz Anything holding us back from releasing in indigo?

**Comment by dlaz** [comment]
Compiles fine for me in indigo/14.04, but it looks like OpenCV's haar cascade xml file may have moved. I'll investigate and create an issue/PR if appropriate.

**Comment by dlaz** [comment]
With #15 resolved, I'm ready to release into indigo unless we want to split off social_navigation_layers first.

**Comment by dlaz** [comment]
ros/rosdistro#6479
