### ISSUE TITLE
OpenCV haarcascades have moved

### ISSUE THREAD

**Issue by dlaz** [wg-perception/people#15]
Need to point to the right location for #14.

**Comment by dlaz** [comment]
Load the haar cascade from /usr/share/opencv/haarcascades/haarcascade_frontalface_alt.xml. This is the location in Ubuntu 14.04 with OpenCV 2.4.8. Ideally, there would be a way to get this programmatically, but it's not clear how to do that.

**Comment by DLu** [comment]
@vrabaud Do you know a programmatic way to do this?

**Comment by vrabaud** [comment]
no way as you can specify different share folders at install time. The easiest is to have code that tries different locations.

**Comment by dlaz** [comment]
In that case, let's just release as-is. We can update share locations when/if people file issues.
