### ISSUE TITLE
Filtered People Velocity tracker doesn't seem to function

### ISSUE THREAD

**Issue by ablasdel** [wg-perception/people#24]
The filtered people velocity tracker seems to be having some issues.

I created an unfiltered people velocity tracker here: https://github.com/wg-perception/people/pull/23
It works fine and people show up in rviz.

When running the filtered no people markers show up in rviz.

**Comment by DLu** [comment]
What was your setup? In particular, what was your laser topic, and did you have a static map?

**Comment by ablasdel** [comment]
I blew away the workspace I had this in awhile ago unfortunately. what does the filter do exactly? we were remapping our laser topic to the standard.

 But I was not publishing a map of any kind. is the filter based on the map topic somehow? if so that is what I was doing wrong.

**Comment by DLu** [comment]
The filtered part was specifically to remove laser readings that corresponded with points in the map.

**Comment by ablasdel** [comment]
well then... this was a mistake on my part I thought it was to filter out laser noise...
