### ISSUE TITLE
Enable tests

### ISSUE THREAD

**Issue by dlaz** [wg-perception/people#32]
When I catkinized this package, I wasn't able to get the tests working. Given PRs like #30, tests which can be run automatically would be helpful.

**Comment by 130s** [comment]
+1 (and sorry for breaking things up).

Today I'll have some time to work on this pkg, so unless someone else is interested I'll try to open a PR.

**Comment by dlaz** [comment]
That would be great!

**Comment by 130s** [comment]
@dlaz I enabled unit tests in #33.
To fully utilize tests, can we enable travis (someone who has admin access)?

**Comment by dlaz** [comment]
I enabled travis, but someone will have to make a .travis.yml in the root of the repo. [moveit_ros](https://github.com/ros-planning/moveit_ros/blob/jade-devel/.travis.yml) looks like it has a good example.

**Comment by 130s** [comment]
You can assign me for .travis. I'll include one in #33.
