### ISSUE TITLE
Not able to run leg_detection. 

### ISSUE THREAD

**Issue by krishnaallani** [wg-perception/people#42]
Hello,

I am working on leg_detection. I am using Ubuntu 14.04, ros-Indigo, with a turtlebot. whenever i run:

> roslaunch leg_detector leg_detector.launch

I am getting the following error:

> [WARN] [1466630966.002926837]: MessageFilter [target=odom_combined ]: Dropped 100.00% of messages so far. Please turn the [ros.leg_detector.message_notifier] rosconsole logger to DEBUG for more information.

I did go through the old questions related to this error in ros answers and changed my fixed_frame from:

> odom_comined to odom

when i changed my fixed frame and ran:

> rostopic echo /camera_tracker_measurements

it outputs nothing. can someone help me with this?

**Comment by DLu** [comment]
This would likely be better handled on answers.ros.org. However, I'm not sure why you would expect output on `camera_tracker_measurements`.

**Comment by beduffy** [comment]
I have this same problem, even after changing every single mention of the word "odom" in the repo to "odom_combined". My guess is that this warning is coming from outside the repo e.g. robot pose ekf or another kalman filter library. Using kinetic branch.

**Comment by beduffy** [comment]
I fixed it by adding:
`<param name="fixed_frame" value="odom"/>`

Within the node of leg_detector.launch file
