### ISSUE TITLE
leg_detector kinetic rtree issue

### ISSUE THREAD

**Issue by hvpandya** [wg-perception/people#44]
I observed @DLu started porting leg_detector to kinetic by changing CvRTrees to  cv::ml::RTrees.

The new OpenCV 3.0 [RTrees](http://docs.opencv.org/3.0-beta/modules/ml/doc/random_trees.html) class does not have direct replacement members for load(), predict_prob() and get_active_var_mask() which are used in leg_detector.

I am unaware of the efforts going on to put those functions in OpenCV 3 or the efforts on modifying leg_detector to work with CV3 as is.

@DLu are you currently pursuing this actively or know about an effort in this direction? I might be able to contribute in my spare time, but I would rather not dive into it if someone is close to solving this issue.

Thanks,
Harsh

**Comment by DLu** [comment]
Hi Harsh. 
I would greatly welcome your time with this. I was trying to get the code to compile in kinetic, and got as far as figuring out the new class name for CvRTrees. After that, I realized it was going to be a bit more work than I had time for.

**Comment by kdhansen** [comment]
I have it compiling now. I need to check the detector when I get back to the lab Monday. I will send a pull request if it checks out.

**Comment by DLu** [comment]
@kdhansen Any luck?

**Comment by kdhansen** [comment]
So it works on my end on a Turtlebot 2. But as you can see in the pull request #48 Travis cannot test Kinetic code. So if someone could check that it also works for them, that would be great.

**Comment by DLu** [comment]
I am unclear what's going wrong with Travis here. Perhaps post it on answers.ros.org?

**Comment by kdhansen** [comment]
As I understand it, the Travis service only supports Precise and Trusty, neither is supported for Kinetic. However it seems @130s has a fix in #49 by running a Docker container.

**Comment by hvpandya** [comment]
@kdhansen any movement on this?

**Comment by kdhansen** [comment]
@hvpandya None, I have not had time to look at it. And it seems @130s also has trouble making the Travis Xenial/Kinetic run. That being said, the code runs fine on my Xenial/Kinetic installation, if you just need it to run.

**Comment by 130s** [comment]
See https://github.com/wg-perception/people/pull/48#issuecomment-280802732 for the progress with Travis CI.

**Comment by DLu** [comment]
Closed via #53
