### ISSUE TITLE
Cascade File haarcascade_frontalface_alt.xml

### ISSUE THREAD

**Issue by X-Bar** [wg-perception/people#45]
Moving from ROS Hydro to Indigo on the PR2 robot (via Clearpath Robotics upgrade), face_detector did not work. 
I have purged and reinstalled through apt-get and used git clone. 

When running 
$ roslaunch face_detector face_detector.wide.launch​
I get
[ERROR]: Cascade file /usr/share/opencv/haarcascades/haarcascade_frontalface_alt.xml doesn't exist.

I have found the file at the following locations. 
$ locate haarcascade_frontalface
/opt/ros/indigo/share/OpenCV-3.1.0-dev/haarcascades/haarcascade_frontalface_alt.xml
/opt/ros/indigo/share/OpenCV-3.1.0-dev/haarcascades/haarcascade_frontalface_alt2.xml
/opt/ros/indigo/share/OpenCV-3.1.0-dev/haarcascades/haarcascade_frontalface_alt_tree.xml
/opt/ros/indigo/share/OpenCV-3.1.0-dev/haarcascades/haarcascade_frontalface_default.xml

Is there a solution to this other than sudo cp?

Thanks

**Comment by DLu** [comment]
Blame opencv for changing their package structure. :)

In order to fix the binary, the parameter for the haarcascade should probably be managed by a parameter. Pull requests are welcome. 

Instead of cp, I would recommend symlinking the OpenCV directory (for a short term solution)

**Comment by X-Bar** [comment]
Hi, thank you for your reply. I did try using a param to look for the file in the new location but I believe that face_detector is not compatible with opencv3, so I revered the pr2 (indigo) to opencv2. 
I had a discussion on ROS Answers I should link. 
http://answers.ros.org/question/242325/error-cascade-file-haarcascade_frontalface_altxml/
