### ISSUE TITLE
people package uninstallable in kinetic

### ISSUE THREAD

**Issue by tfoote** [wg-perception/people#47]
Due to dependencies on unreleased packages: https://github.com/ros/rosdistro/pull/12313

```
$ sudo apt install ros-kinetic-people
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-kinetic-people : Depends: ros-kinetic-leg-detector but it is not installable
                      Depends: ros-kinetic-people-velocity-tracker but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by 130s** [comment]
I assume the best solution is to remove the not-building packages from dependency from the meta-pkg `people`. 
However, Kinetic version is released from `indigo-devel` branch, which means that Indigo release will be affected with what I said. Maybe time for making `kinetic-devel` branch? @dlaz @DLu

**Comment by DLu** [comment]
Possibly fixed with 0bda254faade07474ee11dc952b0664ea4d1260e

**Comment by tfoote** [comment]
That should fix it.

**Comment by DLu** [comment]
I got a [working build](https://travis-ci.org/wg-perception/people) so I'ma gonna close this.
