### ISSUE TITLE
What is dataset to train random forest of the leg detector?

### ISSUE THREAD

**Issue by kmotohas** [wg-perception/people#56]
I would like to know what kind of dataset you used to train random forest of the leg detector.
Our AGV-like robot often recognizes a pillar as legs wrongly.
I am wondering if some parameters and/or LIDAR position need to be tuned somehow.
Information on the training dataset is really helpful for this kind of debug.

Could you please add short documentation on the dataset?

**Comment by kdhansen** [comment]
On the ROS wiki for the leg detector (http://wiki.ros.org/leg_detector) it says: "Sadly, the training dataset has been lost to Willow Garage history (it wasn't even available before they closed). The code is in the repository for retraining, but is unsupported at this time."
