### ISSUE TITLE
problrm about legdetect input message 

### ISSUE THREAD

**Issue by liusanchuan** [wg-perception/people#58]
I want to use the ROS people package in Indigo [https://github.com/wg-perception/people ],
I launch the legdetect file [https://github.com/DLu/people/blob/master/leg_detector/launch/leg_detector.launch],
and give the basic laser scan message.
I dont konw why the node didn't work, can you give me some advice or give me your using launch file .thank you

**Comment by dlaz** [comment]
Can you ask this at [ROS Answers](http://answers.ros.org) instead? More people will see your question there.
