### ISSUE TITLE
face_detector 1.1.0 failing to build on kinetic

### ISSUE THREAD

**Issue by tfoote** [wg-perception/people#63]
From: https://github.com/ros/rosdistro/pull/18991

This appears to have broken face_detector on kinetic http://build.ros.org/job/Kbin_uX32__face_detector__ubuntu_xenial_i386__binary/ and http://build.ros.org/view/Kbin_uxhf_uXhf/job/Kbin_uxhf_uXhf__face_detector__ubuntu_xenial_armhf__binary/

It's passing on armv8 suggesting a race condition.

I suspect it needs the fix called out in wg-perception/people#62 for lunar and higher too

**Comment by DLu** [comment]
Now on 1.1.2
