### ISSUE TITLE
Port people_msgs to ROS 2 Dashing

### ISSUE THREAD

**Issue by sloretz** [wg-perception/people#69]
Mind answering a few questions about porting `people_msgs` to ROS 2 Dashing?

* Has anyone started porting these packages to ROS 2?
* Would the maintainer be willing to release just `people_msgs` into dashing, or does everything in the repo need to be ported first?
* Where should a port live? How about in this repo in a `dashing` branch?

**Comment by DLu** [comment]
No one has started any ROS 2 work to my knowledge (except you).

What are you using `people_msgs` for outside of this repo, out of curiosity? 

I made a new `ros1` branch, and once I merge one more PR, I will make a `ros2` branch to go alongside it.
