### ISSUE TITLE
orocos-bfl absent compile error melodic

### ISSUE THREAD

**Issue by FrGe2016** [wg-perception/people#80]
When i compile on melodic i have the following message 

-- ==> add_subdirectory(unit_8/people/people_tracking_filter)
-- Checking for module 'ros-melodic-bfl'
--   No package 'orocos-bfl' found

When i **locate orocos-bfl** i have the following result
/opt/ros/melodic/lib/liborocos-bfl.so
/opt/ros/melodic/lib/pkgconfig/orocos-bfl.pc

but roscd orocos-bfl
roscd: No such package/stack 'orocos-bfl'

When i look in the wiki i am told that orocos-bfl in included in the melodic package under bfl
i fin a lot of files under /usr/share/doc/ros-melodic-bfl or /usr/share/doc/ros-melodic-bfl.

but roscd ros-melodic-bfl or roscd bfl gives
No such package/stack ....

It is looking that bfl is ther but not available ?

**Comment by DLu** [comment]
* Which operating system are you using? 
 * orocos_bfl is not a ROS package, but an external dependency. 
 * Have you installed all of the upstream dependencies?

**Comment by FrGe2016** [comment]
I am using ubuntu 18

So the ROS BFL package would have noting to do with the requirement of
orocos-bfl.
Any procedure to install orocos_bfl as a "normal" linux package?

**Comment by DLu** [comment]
Can you run `rosdep install --ignore-src -y -r --from-paths PATH/TO/PEOPLE_REPO`
