### ISSUE TITLE
Problem with leg_detector, only publish legs on the topic visualizer_marker

### ISSUE THREAD

**Issue by Dagu12s** [wg-perception/people#81]
Im running the leg_detector in a simulated enviroment and i dont know why, when i run the leg_detector, it does not detect anything, it publish in all the topics but empty. The thing is that in the topic: Visualizer_marker, it detects the legs of the person, but only the legs (it print the LEGS in rviz)
see the topics here: 

/leg_tracker_measurements
header: 
  seq: 11178
  stamp: 
    secs: 1002
    nsecs:  17000000
  frame_id: ''
people: []
cooccurrence: []

/people_tracker_measurements
header: 
  seq: 609
  stamp: 
    secs: 49
    nsecs: 440000000
  frame_id: ''
people: []
cooccurrence: []

/visualizer_marker
header: 
  seq: 865
  stamp: 
    secs: 114
    nsecs: 995000000
  frame_id: "robot_odom"
ns: "LEGS"
id: 1
type: 2
action: 0
pose: 
  position: 
    x: 2.08340144953
    y: -0.260147165313
    z: 0.308259475206
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 0.0
scale: 
  x: 0.1
  y: 0.1
  z: 0.1
color: 
  r: 0.0
  g: 0.0
  b: 0.33749806881
  a: 1.0
lifetime: 
  secs: 0
  nsecs: 500000000
frame_locked: False
points: []
colors: []
text: ''
mesh_resource: ''
mesh_use_embedded_materials: False

Any idea?

**Comment by DLu** [comment]
We can discuss it [here](https://answers.ros.org/question/354069/leg_detector-only-publish-on-visualization_marker-and-only-legs-no-people/). Please don't cross-post.
