### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [wg-perception/people#83]
We don't use this package ourselves, but it's a dependency of [jsk_rviz_plugins](https://github.com/jsk-ros-pkg/jsk_visualization/issues/772)

So could this be released for Noetic? :)

**Comment by DLu** [comment]
I've started a branch [here,](https://github.com/DLu/people/tree/noetic) but don't have time to chase everything down. Current issues: 
 * `people_tracking_filter` needs an update to the CMake for BFL
 * `face_detector` is having trouble including opencv files.

**Comment by PeterMitrano** [comment]
I believe https://github.com/DLu/wu_ros_tools will also need a noetic release, beacuse JSK stuff depends on `easy_markers`

**Comment by DLu** [comment]
Ready to go, pending https://github.com/ros/rosdistro/pull/26602

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/26639

Note, the current noetic release only contains `people_msgs` and `people_velocity_tracker`. Additional work is needed to get the other packages to work.
