### ISSUE TITLE
Training new legs

### ISSUE THREAD

**Issue by Axelito95** [wg-perception/people#92]
Hello! 

I would like to create a new training file. I didn't found a documentation about the legs training. I just found train_leg_detector.cpp to compile and run.

Firstly i would like to know what type inputs and files it take in parameters. the data input could be just a bagfile of my lidar?

Second, should i run the trainer with all arguments ?

Exemple : ./trainer --train file.bag --neg file2.bag --test file3.bag --save

Have u some suggestions to make a good training?

**Comment by DLu** [comment]
As noted on [the wiki](http://wiki.ros.org/leg_detector#The_Leg_Detector), retraining is unsupported at this time. So at this time, I don't have any useful suggestions.

**Comment by Axelito95** [comment]
ok thanks
